name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    name: Check lint and prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint
      - run: npm run prettier
        env:
          CI: true
  test:
    name: Test on node 20 and ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm install
      - run: npm test
        env:
          CI: true
